// lang.js — Multi-language support (17 languages)
const LANG = {
    en: {
        langName: "English", totalBalance: "TOTAL BALANCE", connect: "Connect", connected: "Connected",
        ghsUnit: "GH/s", networkStatus: "Network Status", offline: "Offline ○", mining: "Mining ●",
        active: "Active", activeDevices: "Active Devices", dailyTon: "Daily TON",
        freeNode: "FREE Node", freeNodeDesc: "+300 GH/s (30 min)", watch: "WATCH",
        joinChannel: "Join Our Channel", channelDesc: "News & giveaways",
        dailySpin: "Daily Spin", spinDesc: "Spin to win free TON!", nextSpinIn: "Next spin in", free: "FREE",
        bronze: "Bronze", silver: "Silver", gold: "Gold", diamond: "Diamond", legendary: "Legendary",
        maxRank: "MAX RANK", tonEarned: "TON earned", toNext: "to",
        dailyFortune: "Daily Fortune", spinToWin: "SPIN TO WIN", spinning: "Spinning...",
        addedBalance: "Added to your balance!", nextSpinInLabel: "Next spin in:",
        hardwareStore: "Hardware Store", tonDay: "TON/day", roi: "ROI", days: "days",
        myDevices: "My Devices", empty: "Empty", bonus: "BONUS",
        withdraw: "Withdraw TON", enterAmount: "Enter Amount", minWithdraw: "Minimum 100 TON",
        walletAddress: "Wallet Address", withdrawBtn: "Withdraw", connectFirst: "Connect Wallet!",
        invalidAmount: "Invalid amount!", minRequired: "Minimum 100 TON", noBalance: "Not enough balance!",
        referralTitle: "Referral Program", yourCode: "Your Code", totalRefs: "Total Referrals",
        commission: "Commission", shareLink: "Share Referral Link", copied: "Copied!",
        terms: "Terms of Service", privacy: "Privacy Policy", lastUpdated: "Last Updated",
        offlineTitle: "Welcome Back!", offlineSub: "Your miners worked while you were away",
        dailyReward: "Daily Reward", claimReward: "CLAIM REWARD", day: "Day",
        sent: "Sending...", cancelled: "Cancelled", opening: "Opening...",
        tasksTitle: "Tasks & Achievements", tasksSubtitle: "Complete tasks to earn bonus TON!",
        taskConnectWallet: "Connect Wallet", taskConnectWalletDesc: "Connect your TON wallet",
        taskFirstMachine: "First Machine", taskFirstMachineDesc: "Buy your first mining machine",
        taskBuy5: "Machine Collector", taskBuy5Desc: "Own 5 mining machines",
        taskBuy10: "Mining Farm", taskBuy10Desc: "Own 10 mining machines",
        taskFirstSpin: "Lucky Spinner", taskFirstSpinDesc: "Use the daily spin wheel",
        taskWatchAd: "Ad Watcher", taskWatchAdDesc: "Watch an ad for free hashrate",
        taskInvite1: "First Referral", taskInvite1Desc: "Invite 1 friend",
        taskInvite5: "Team Builder", taskInvite5Desc: "Invite 5 friends",
        taskInvite20: "Network Master", taskInvite20Desc: "Invite 20 friends",
        taskLogin7: "7-Day Streak", taskLogin7Desc: "Login 7 days in a row",
        taskEarn10: "First Milestone", taskEarn10Desc: "Earn 10 TON total",
        taskEarn100: "TON Whale", taskEarn100Desc: "Earn 100 TON total",
        taskSilver: "Silver Rank", taskSilverDesc: "Reach Silver rank",
        taskGold: "Gold Rank", taskGoldDesc: "Reach Gold rank",
        taskDiamond: "Diamond Rank", taskDiamondDesc: "Reach Diamond rank",
        completed: "Completed", claim: "CLAIM"
    },
    tr: {
        langName: "Türkçe", totalBalance: "TOPLAM BAKİYE", connect: "Bağlan", connected: "Bağlı",
        ghsUnit: "GH/s", networkStatus: "Ağ Durumu", offline: "Çevrimdışı ○", mining: "Kazım Aktif ●",
        active: "Aktif", activeDevices: "Aktif Cihaz", dailyTon: "Günlük TON",
        freeNode: "ÜCRETSİZ Node", freeNodeDesc: "+300 GH/s (30 dk)", watch: "İZLE",
        joinChannel: "Kanalımıza Katıl", channelDesc: "Haberler ve çekilişler",
        dailySpin: "Günlük Çark", spinDesc: "Çevir, bedava TON kazan!", nextSpinIn: "Sonraki çevirme", free: "BEDAVA",
        bronze: "Bronz", silver: "Gümüş", gold: "Altın", diamond: "Elmas", legendary: "Efsanevi",
        maxRank: "MAKS SEVİYE", tonEarned: "TON kazanıldı", toNext: "→",
        dailyFortune: "Günlük Şans", spinToWin: "ÇEVİR & KAZAN", spinning: "Dönüyor...",
        addedBalance: "Bakiyenize eklendi!", nextSpinInLabel: "Sonraki çevirme:",
        hardwareStore: "Donanım Mağazası", tonDay: "TON/gün", roi: "Amorti", days: "gün",
        myDevices: "Cihazlarım", empty: "Boş", bonus: "BONUS",
        withdraw: "TON Çek", enterAmount: "Miktar Girin", minWithdraw: "Minimum 100 TON",
        walletAddress: "Cüzdan Adresi", withdrawBtn: "Çekim Yap", connectFirst: "Cüzdan bağlayın!",
        invalidAmount: "Geçersiz miktar!", minRequired: "Minimum 100 TON", noBalance: "Yetersiz bakiye!",
        referralTitle: "Referans Programı", yourCode: "Kodunuz", totalRefs: "Toplam Referans",
        commission: "Komisyon", shareLink: "Referans Linkini Paylaş", copied: "Kopyalandı!",
        terms: "Kullanım Şartları", privacy: "Gizlilik Politikası", lastUpdated: "Son Güncelleme",
        offlineTitle: "Tekrar Hoşgeldin!", offlineSub: "Madencilerin sen yokken çalıştı",
        dailyReward: "Günlük Ödül", claimReward: "ÖDÜLÜ AL", day: "Gün",
        sent: "Gönderiliyor...", cancelled: "İptal Edildi", opening: "Açılıyor...",
        tasksTitle: "Görevler & Başarılar", tasksSubtitle: "Görevleri tamamla, bonus TON kazan!",
        taskConnectWallet: "Cüzdan Bağla", taskConnectWalletDesc: "TON cüzdanını bağla",
        taskFirstMachine: "İlk Makine", taskFirstMachineDesc: "İlk madencilik makineni al",
        taskBuy5: "Makine Koleksiyoncusu", taskBuy5Desc: "5 makineye sahip ol",
        taskBuy10: "Madencilik Çiftliği", taskBuy10Desc: "10 makineye sahip ol",
        taskFirstSpin: "Şanslı Çevirici", taskFirstSpinDesc: "Günlük çarkı çevir",
        taskWatchAd: "Reklam İzleyici", taskWatchAdDesc: "Ücretsiz hashrate için reklam izle",
        taskInvite1: "İlk Davet", taskInvite1Desc: "1 arkadaş davet et",
        taskInvite5: "Takım Kurucu", taskInvite5Desc: "5 arkadaş davet et",
        taskInvite20: "Ağ Ustası", taskInvite20Desc: "20 arkadaş davet et",
        taskLogin7: "7 Gün Seri", taskLogin7Desc: "7 gün üst üste giriş yap",
        taskEarn10: "İlk Kilometre Taşı", taskEarn10Desc: "Toplam 10 TON kazan",
        taskEarn100: "TON Balinası", taskEarn100Desc: "Toplam 100 TON kazan",
        taskSilver: "Gümüş Rütbe", taskSilverDesc: "Gümüş rütbeye ulaş",
        taskGold: "Altın Rütbe", taskGoldDesc: "Altın rütbeye ulaş",
        taskDiamond: "Elmas Rütbe", taskDiamondDesc: "Elmas rütbeye ulaş",
        completed: "Tamamlandı", claim: "AL"
    },
    zh: {
        langName: "中文", totalBalance: "总余额", connect: "连接", connected: "已连接",
        ghsUnit: "GH/s", networkStatus: "网络状态", offline: "离线 ○", mining: "挖矿中 ●",
        active: "活跃", activeDevices: "活跃设备", dailyTon: "日收益",
        freeNode: "免费节点", freeNodeDesc: "+300 GH/s (30分钟)", watch: "观看",
        joinChannel: "加入频道", channelDesc: "新闻和活动",
        dailySpin: "每日转盘", spinDesc: "转动赢取免费TON!", nextSpinIn: "下次转盘", free: "免费",
        bronze: "青铜", silver: "白银", gold: "黄金", diamond: "钻石", legendary: "传奇",
        maxRank: "最高等级", tonEarned: "已赚TON", toNext: "→",
        dailyFortune: "每日幸运", spinToWin: "转动赢取", spinning: "旋转中...",
        addedBalance: "已添加到余额!", nextSpinInLabel: "下次转盘:",
        hardwareStore: "硬件商店", tonDay: "TON/天", roi: "回本", days: "天",
        myDevices: "我的设备", empty: "空", bonus: "奖励",
        withdraw: "提取TON", enterAmount: "输入金额", minWithdraw: "最低100 TON",
        walletAddress: "钱包地址", withdrawBtn: "提取", connectFirst: "请连接钱包!",
        invalidAmount: "无效金额!", minRequired: "最低100 TON", noBalance: "余额不足!",
        referralTitle: "推荐计划", yourCode: "您的代码", totalRefs: "总推荐",
        commission: "佣金", shareLink: "分享推荐链接", copied: "已复制!",
        terms: "服务条款", privacy: "隐私政策", lastUpdated: "最后更新",
        offlineTitle: "欢迎回来!", offlineSub: "您不在时矿机一直在工作",
        dailyReward: "每日奖励", claimReward: "领取奖励", day: "天",
        sent: "发送中...", cancelled: "已取消", opening: "打开中...",
        tasksTitle: "任务和成就", tasksSubtitle: "完成任务赚取奖励TON！",
        taskConnectWallet: "连接钱包", taskConnectWalletDesc: "连接你的TON钱包",
        taskFirstMachine: "第一台矿机", taskFirstMachineDesc: "购买你的第一台矿机",
        taskBuy5: "矿机收藏家", taskBuy5Desc: "拥有5台矿机",
        taskBuy10: "矿场", taskBuy10Desc: "拥有10台矿机",
        taskFirstSpin: "幸运转盘", taskFirstSpinDesc: "使用每日转盘",
        taskWatchAd: "广告观看者", taskWatchAdDesc: "观看广告获得免费算力",
        taskInvite1: "首次邀请", taskInvite1Desc: "邀请1位好友",
        taskInvite5: "团队建设者", taskInvite5Desc: "邀请5位好友",
        taskInvite20: "网络大师", taskInvite20Desc: "邀请20位好友",
        taskLogin7: "7天连续", taskLogin7Desc: "连续登录7天",
        taskEarn10: "第一个里程碑", taskEarn10Desc: "总共赚取10 TON",
        taskEarn100: "TON鲸鱼", taskEarn100Desc: "总共赚取100 TON",
        taskSilver: "白银段位", taskSilverDesc: "达到白银段位",
        taskGold: "黄金段位", taskGoldDesc: "达到黄金段位",
        taskDiamond: "钻石段位", taskDiamondDesc: "达到钻石段位",
        completed: "已完成", claim: "领取"
    },
    ja: {
        langName: "日本語", totalBalance: "合計残高", connect: "接続", connected: "接続済み",
        ghsUnit: "GH/s", networkStatus: "ネットワーク状態", offline: "オフライン ○", mining: "マイニング中 ●",
        active: "アクティブ", activeDevices: "稼働デバイス", dailyTon: "日次TON",
        freeNode: "無料ノード", freeNodeDesc: "+300 GH/s (30分)", watch: "視聴",
        joinChannel: "チャンネル参加", channelDesc: "ニュースとイベント",
        dailySpin: "デイリースピン", spinDesc: "回して無料TONをゲット!", nextSpinIn: "次のスピン", free: "無料",
        bronze: "ブロンズ", silver: "シルバー", gold: "ゴールド", diamond: "ダイヤモンド", legendary: "レジェンド",
        maxRank: "最高ランク", tonEarned: "獲得TON", toNext: "→",
        dailyFortune: "デイリーフォーチュン", spinToWin: "回して勝つ", spinning: "回転中...",
        addedBalance: "残高に追加!", nextSpinInLabel: "次のスピン:",
        hardwareStore: "ハードウェアストア", tonDay: "TON/日", roi: "回収", days: "日",
        myDevices: "マイデバイス", empty: "空", bonus: "ボーナス",
        withdraw: "TON引出", enterAmount: "金額入力", minWithdraw: "最低100 TON",
        walletAddress: "ウォレットアドレス", withdrawBtn: "引き出す", connectFirst: "ウォレットを接続!",
        invalidAmount: "無効な金額!", minRequired: "最低100 TON", noBalance: "残高不足!",
        referralTitle: "紹介プログラム", yourCode: "あなたのコード", totalRefs: "総紹介数",
        commission: "コミッション", shareLink: "紹介リンクを共有", copied: "コピー済み!",
        terms: "利用規約", privacy: "プライバシーポリシー", lastUpdated: "最終更新",
        offlineTitle: "おかえりなさい!", offlineSub: "留守中もマイナーが稼働していました",
        dailyReward: "デイリー報酬", claimReward: "報酬を受け取る", day: "日目",
        sent: "送信中...", cancelled: "キャンセル", opening: "開いています...",
        tasksTitle: "タスク＆実績", tasksSubtitle: "タスクを完成してTONを獲得！"
    },
    ko: {
        langName: "한국어", totalBalance: "총 잔액", connect: "연결", connected: "연결됨",
        ghsUnit: "GH/s", networkStatus: "네트워크 상태", offline: "오프라인 ○", mining: "채굴중 ●",
        active: "활성", activeDevices: "활성 장치", dailyTon: "일일 TON",
        freeNode: "무료 노드", freeNodeDesc: "+300 GH/s (30분)", watch: "시청",
        joinChannel: "채널 참여", channelDesc: "뉴스 및 이벤트",
        dailySpin: "일일 룰렛", spinDesc: "돌려서 무료 TON!", nextSpinIn: "다음 스핀", free: "무료",
        bronze: "브론즈", silver: "실버", gold: "골드", diamond: "다이아몬드", legendary: "레전드",
        maxRank: "최고 등급", tonEarned: "획득 TON", toNext: "→",
        dailyFortune: "일일 행운", spinToWin: "돌려서 승리", spinning: "회전중...",
        addedBalance: "잔액에 추가!", nextSpinInLabel: "다음 스핀:",
        hardwareStore: "하드웨어 상점", tonDay: "TON/일", roi: "회수", days: "일",
        myDevices: "내 장치", empty: "비어있음", bonus: "보너스",
        withdraw: "TON 출금", enterAmount: "금액 입력", minWithdraw: "최소 100 TON",
        walletAddress: "지갑 주소", withdrawBtn: "출금", connectFirst: "지갑을 연결하세요!",
        invalidAmount: "잘못된 금액!", minRequired: "최소 100 TON", noBalance: "잔액 부족!",
        referralTitle: "추천 프로그램", yourCode: "내 코드", totalRefs: "총 추천수",
        commission: "수수료", shareLink: "추천 링크 공유", copied: "복사됨!",
        terms: "이용약관", privacy: "개인정보처리방침", lastUpdated: "최종 업데이트",
        offlineTitle: "돌아오셨군요!", offlineSub: "부재중에도 채굴기가 작동했습니다",
        dailyReward: "일일 보상", claimReward: "보상 받기", day: "일차",
        sent: "전송중...", cancelled: "취소됨", opening: "여는 중...",
        tasksTitle: "과제 & 업적", tasksSubtitle: "과제를 완료하고 보너스 TON을 받으세요!"
    },
    hi: {
        langName: "हिन्दी", totalBalance: "कुल शेष", connect: "कनेक्ट", connected: "कनेक्टेड",
        ghsUnit: "GH/s", networkStatus: "नेटवर्क स्थिति", offline: "ऑफ़लाइन ○", mining: "माइनिंग ●",
        active: "सक्रिय", activeDevices: "सक्रिय डिवाइस", dailyTon: "दैनिक TON",
        freeNode: "मुफ़्त नोड", freeNodeDesc: "+300 GH/s (30 मिनट)", watch: "देखें",
        joinChannel: "चैनल जॉइन करें", channelDesc: "समाचार और उपहार",
        dailySpin: "दैनिक स्पिन", spinDesc: "घुमाकर मुफ़्त TON जीतें!", nextSpinIn: "अगला स्पिन", free: "मुफ़्त",
        bronze: "कांस्य", silver: "रजत", gold: "स्वर्ण", diamond: "हीरा", legendary: "दिग्गज",
        maxRank: "अधिकतम रैंक", tonEarned: "अर्जित TON", toNext: "→",
        dailyFortune: "दैनिक भाग्य", spinToWin: "घुमाएं और जीतें", spinning: "घूम रहा...",
        addedBalance: "बैलेंस में जोड़ा गया!", nextSpinInLabel: "अगला स्पिन:",
        hardwareStore: "हार्डवेयर स्टोर", tonDay: "TON/दिन", roi: "वापसी", days: "दिन",
        myDevices: "मेरे डिवाइस", empty: "खाली", bonus: "बोनस",
        withdraw: "TON निकालें", enterAmount: "राशि दर्ज करें", minWithdraw: "न्यूनतम 100 TON",
        walletAddress: "वॉलेट पता", withdrawBtn: "निकालें", connectFirst: "वॉलेट कनेक्ट करें!",
        invalidAmount: "अमान्य राशि!", minRequired: "न्यूनतम 100 TON", noBalance: "अपर्याप्त शेष!",
        referralTitle: "रेफरल प्रोग्राम", yourCode: "आपका कोड", totalRefs: "कुल रेफरल",
        commission: "कमीशन", shareLink: "रेफरल लिंक शेयर करें", copied: "कॉपी हो गया!",
        terms: "सेवा की शर्तें", privacy: "गोपनीयता नीति", lastUpdated: "अंतिम अपडेट",
        offlineTitle: "वापस स्वागत है!", offlineSub: "आपकी अनुपस्थिति में माइनर काम कर रहे थे",
        dailyReward: "दैनिक इनाम", claimReward: "इनाम लें", day: "दिन",
        sent: "भेज रहा है...", cancelled: "रद्द", opening: "खुल रहा है...",
        tasksTitle: "कार्य और उपलब्धियाँ", tasksSubtitle: "कार्य पूरा करें, बोनस TON कमाएं!"
    },
    ur: {
        langName: "اردو", totalBalance: "کل بیلنس", connect: "جوڑیں", connected: "جڑا ہوا",
        ghsUnit: "GH/s", networkStatus: "نیٹ ورک حالت", offline: "آف لائن ○", mining: "مائننگ ●",
        active: "فعال", activeDevices: "فعال آلات", dailyTon: "روزانہ TON",
        freeNode: "مفت نوڈ", freeNodeDesc: "+300 GH/s (30 منٹ)", watch: "دیکھیں",
        joinChannel: "چینل جوائن کریں", channelDesc: "خبریں اور انعامات",
        dailySpin: "روزانہ اسپن", spinDesc: "گھمائیں اور مفت TON جیتیں!", nextSpinIn: "اگلا اسپن", free: "مفت",
        bronze: "کانسی", silver: "چاندی", gold: "سونا", diamond: "ہیرا", legendary: "لیجنڈری",
        maxRank: "اعلیٰ درجہ", tonEarned: "حاصل TON", toNext: "→",
        dailyFortune: "روزانہ قسمت", spinToWin: "گھمائیں اور جیتیں", spinning: "گھوم رہا ہے...",
        addedBalance: "بیلنس میں شامل!", nextSpinInLabel: "اگلا اسپن:",
        hardwareStore: "ہارڈویئر اسٹور", tonDay: "TON/دن", roi: "واپسی", days: "دن",
        myDevices: "میرے آلات", empty: "خالی", bonus: "بونس",
        withdraw: "TON نکالیں", enterAmount: "رقم درج کریں", minWithdraw: "کم از کم 100 TON",
        walletAddress: "والیٹ ایڈریس", withdrawBtn: "نکالیں", connectFirst: "والیٹ جوڑیں!",
        invalidAmount: "غلط رقم!", minRequired: "کم از کم 100 TON", noBalance: "ناکافی بیلنس!",
        referralTitle: "ریفرل پروگرام", yourCode: "آپ کا کوڈ", totalRefs: "کل ریفرلز",
        commission: "کمیشن", shareLink: "ریفرل لنک شیئر کریں", copied: "کاپی ہو گیا!",
        terms: "شرائط", privacy: "رازداری پالیسی", lastUpdated: "آخری اپڈیٹ",
        offlineTitle: "واپس خوش آمدید!", offlineSub: "آپ کی غیر موجودگی میں مائنرز کام کر رہے تھے",
        dailyReward: "روزانہ انعام", claimReward: "انعام لیں", day: "دن",
        sent: "بھیج رہا ہے...", cancelled: "منسوخ", opening: "کھل رہا ہے...",
        tasksTitle: "ٹاسک اور کامیابیاں", tasksSubtitle: "ٹاسک مکمل کریں بونس TON کمائیں!"
    },
    ar: {
        langName: "العربية", totalBalance: "الرصيد الإجمالي", connect: "اتصال", connected: "متصل",
        ghsUnit: "GH/s", networkStatus: "حالة الشبكة", offline: "غير متصل ○", mining: "تعدين ●",
        active: "نشط", activeDevices: "الأجهزة النشطة", dailyTon: "TON يومي",
        freeNode: "عقدة مجانية", freeNodeDesc: "+300 GH/s (30 دقيقة)", watch: "شاهد",
        joinChannel: "انضم للقناة", channelDesc: "أخبار وجوائز",
        dailySpin: "الدولاب اليومي", spinDesc: "أدر واربح TON مجاني!", nextSpinIn: "الدوران التالي", free: "مجاني",
        bronze: "برونزي", silver: "فضي", gold: "ذهبي", diamond: "ماسي", legendary: "أسطوري",
        maxRank: "أعلى رتبة", tonEarned: "TON مكتسب", toNext: "→",
        dailyFortune: "حظ يومي", spinToWin: "أدر واربح", spinning: "يدور...",
        addedBalance: "تمت الإضافة لرصيدك!", nextSpinInLabel: "الدوران التالي:",
        hardwareStore: "متجر الأجهزة", tonDay: "TON/يوم", roi: "الاسترداد", days: "يوم",
        myDevices: "أجهزتي", empty: "فارغ", bonus: "مكافأة",
        withdraw: "سحب TON", enterAmount: "أدخل المبلغ", minWithdraw: "الحد الأدنى 100 TON",
        walletAddress: "عنوان المحفظة", withdrawBtn: "سحب", connectFirst: "اربط المحفظة!",
        invalidAmount: "مبلغ غير صالح!", minRequired: "الحد الأدنى 100 TON", noBalance: "رصيد غير كافٍ!",
        referralTitle: "برنامج الإحالة", yourCode: "رمزك", totalRefs: "إجمالي الإحالات",
        commission: "العمولة", shareLink: "شارك رابط الإحالة", copied: "تم النسخ!",
        terms: "شروط الخدمة", privacy: "سياسة الخصوصية", lastUpdated: "آخر تحديث",
        offlineTitle: "مرحباً بعودتك!", offlineSub: "عمال المناجم عملوا أثناء غيابك",
        dailyReward: "المكافأة اليومية", claimReward: "استلم المكافأة", day: "يوم",
        sent: "جاري الإرسال...", cancelled: "ملغي", opening: "جاري الفتح...",
        tasksTitle: "المهام والإنجازات", tasksSubtitle: "أكمل المهام واكسب TON إضافي!"
    },
    es: {
        langName: "Español", totalBalance: "SALDO TOTAL", connect: "Conectar", connected: "Conectado",
        ghsUnit: "GH/s", networkStatus: "Estado de Red", offline: "Sin conexión ○", mining: "Minando ●",
        active: "Activo", activeDevices: "Dispositivos", dailyTon: "TON Diario",
        freeNode: "Nodo GRATIS", freeNodeDesc: "+300 GH/s (30 min)", watch: "VER",
        joinChannel: "Únete al Canal", channelDesc: "Noticias y sorteos",
        dailySpin: "Giro Diario", spinDesc: "¡Gira y gana TON!", nextSpinIn: "Próximo giro", free: "GRATIS",
        bronze: "Bronce", silver: "Plata", gold: "Oro", diamond: "Diamante", legendary: "Legendario",
        maxRank: "RANGO MÁX", tonEarned: "TON ganados", toNext: "→",
        dailyFortune: "Fortuna Diaria", spinToWin: "GIRA Y GANA", spinning: "Girando...",
        addedBalance: "¡Añadido a tu saldo!", nextSpinInLabel: "Próximo giro:",
        hardwareStore: "Tienda", tonDay: "TON/día", roi: "Retorno", days: "días",
        myDevices: "Mis Dispositivos", empty: "Vacío", bonus: "BONUS",
        withdraw: "Retirar TON", enterAmount: "Ingresa Monto", minWithdraw: "Mínimo 100 TON",
        walletAddress: "Dirección Wallet", withdrawBtn: "Retirar", connectFirst: "¡Conecta Wallet!",
        invalidAmount: "¡Monto inválido!", minRequired: "Mínimo 100 TON", noBalance: "¡Saldo insuficiente!",
        referralTitle: "Programa Referidos", yourCode: "Tu Código", totalRefs: "Total Referidos",
        commission: "Comisión", shareLink: "Compartir Enlace", copied: "¡Copiado!",
        terms: "Términos", privacy: "Privacidad", lastUpdated: "Última Actualización",
        offlineTitle: "¡Bienvenido!", offlineSub: "Tus mineros trabajaron mientras estabas fuera",
        dailyReward: "Recompensa Diaria", claimReward: "RECLAMAR", day: "Día",
        sent: "Enviando...", cancelled: "Cancelado", opening: "Abriendo...",
        tasksTitle: "Tareas y Logros", tasksSubtitle: "¡Completa tareas para ganar TON bonus!"
    },
    pt: {
        langName: "Português", totalBalance: "SALDO TOTAL", connect: "Conectar", connected: "Conectado",
        ghsUnit: "GH/s", networkStatus: "Status da Rede", offline: "Offline ○", mining: "Minerando ●",
        active: "Ativo", activeDevices: "Dispositivos", dailyTon: "TON Diário",
        freeNode: "Nó GRÁTIS", freeNodeDesc: "+300 GH/s (30 min)", watch: "ASSISTIR",
        joinChannel: "Entre no Canal", channelDesc: "Notícias e sorteios",
        dailySpin: "Giro Diário", spinDesc: "Gire e ganhe TON!", nextSpinIn: "Próximo giro", free: "GRÁTIS",
        bronze: "Bronze", silver: "Prata", gold: "Ouro", diamond: "Diamante", legendary: "Lendário",
        maxRank: "RANK MÁX", tonEarned: "TON ganhos", toNext: "→",
        dailyFortune: "Fortuna Diária", spinToWin: "GIRE E GANHE", spinning: "Girando...",
        addedBalance: "Adicionado ao saldo!", nextSpinInLabel: "Próximo giro:",
        hardwareStore: "Loja", tonDay: "TON/dia", roi: "Retorno", days: "dias",
        myDevices: "Meus Dispositivos", empty: "Vazio", bonus: "BÔNUS",
        withdraw: "Sacar TON", enterAmount: "Valor", minWithdraw: "Mínimo 100 TON",
        walletAddress: "Endereço Carteira", withdrawBtn: "Sacar", connectFirst: "Conecte Carteira!",
        invalidAmount: "Valor inválido!", minRequired: "Mínimo 100 TON", noBalance: "Saldo insuficiente!",
        referralTitle: "Programa Indicação", yourCode: "Seu Código", totalRefs: "Total Indicações",
        commission: "Comissão", shareLink: "Compartilhar Link", copied: "Copiado!",
        terms: "Termos", privacy: "Privacidade", lastUpdated: "Última Atualização",
        offlineTitle: "Bem-vindo de volta!", offlineSub: "Seus mineradores trabalharam na sua ausência",
        dailyReward: "Recompensa Diária", claimReward: "COLETAR", day: "Dia",
        sent: "Enviando...", cancelled: "Cancelado", opening: "Abrindo...",
        tasksTitle: "Tarefas e Conquistas", tasksSubtitle: "Complete tarefas para ganhar TON bônus!"
    },
    ru: {
        langName: "Русский", totalBalance: "ОБЩИЙ БАЛАНС", connect: "Подключить", connected: "Подключено",
        ghsUnit: "GH/s", networkStatus: "Статус сети", offline: "Офлайн ○", mining: "Майнинг ●",
        active: "Активно", activeDevices: "Устройства", dailyTon: "TON в день",
        freeNode: "Бесплатный узел", freeNodeDesc: "+300 GH/s (30 мин)", watch: "СМОТРЕТЬ",
        joinChannel: "Наш канал", channelDesc: "Новости и розыгрыши",
        dailySpin: "Ежедневное вращение", spinDesc: "Крутите и выигрывайте!", nextSpinIn: "Следующее", free: "БЕСПЛАТНО",
        bronze: "Бронза", silver: "Серебро", gold: "Золото", diamond: "Алмаз", legendary: "Легенда",
        maxRank: "МАКС РАНГ", tonEarned: "Заработано", toNext: "→",
        dailyFortune: "Ежедневная удача", spinToWin: "КРУТИТЬ", spinning: "Вращение...",
        addedBalance: "Добавлено к балансу!", nextSpinInLabel: "Следующее:",
        hardwareStore: "Магазин", tonDay: "TON/день", roi: "Окупаемость", days: "дней",
        myDevices: "Мои устройства", empty: "Пусто", bonus: "БОНУС",
        withdraw: "Вывод TON", enterAmount: "Сумма", minWithdraw: "Минимум 100 TON",
        walletAddress: "Адрес кошелька", withdrawBtn: "Вывести", connectFirst: "Подключите кошелёк!",
        invalidAmount: "Неверная сумма!", minRequired: "Минимум 100 TON", noBalance: "Недостаточно средств!",
        referralTitle: "Реферальная программа", yourCode: "Ваш код", totalRefs: "Всего рефералов",
        commission: "Комиссия", shareLink: "Поделиться ссылкой", copied: "Скопировано!",
        terms: "Условия", privacy: "Конфиденциальность", lastUpdated: "Обновлено",
        offlineTitle: "С возвращением!", offlineSub: "Ваши майнеры работали пока вас не было",
        dailyReward: "Ежедневная награда", claimReward: "ПОЛУЧИТЬ", day: "День",
        sent: "Отправка...", cancelled: "Отменено", opening: "Открытие...",
        tasksTitle: "Задания и достижения", tasksSubtitle: "Выполняйте задания и получайте бонус TON!"
    },
    id: {
        langName: "Bahasa", totalBalance: "TOTAL SALDO", connect: "Hubungkan", connected: "Terhubung",
        ghsUnit: "GH/s", networkStatus: "Status Jaringan", offline: "Offline ○", mining: "Menambang ●",
        active: "Aktif", activeDevices: "Perangkat Aktif", dailyTon: "TON Harian",
        freeNode: "Node GRATIS", freeNodeDesc: "+300 GH/s (30 mnt)", watch: "TONTON",
        joinChannel: "Gabung Channel", channelDesc: "Berita dan hadiah",
        dailySpin: "Putar Harian", spinDesc: "Putar & menangkan TON!", nextSpinIn: "Putaran berikut", free: "GRATIS",
        bronze: "Perunggu", silver: "Perak", gold: "Emas", diamond: "Berlian", legendary: "Legendaris",
        maxRank: "RANK MAKS", tonEarned: "TON diperoleh", toNext: "→",
        dailyFortune: "Keberuntungan", spinToWin: "PUTAR & MENANG", spinning: "Berputar...",
        addedBalance: "Ditambahkan ke saldo!", nextSpinInLabel: "Putaran berikut:",
        hardwareStore: "Toko Perangkat", tonDay: "TON/hari", roi: "Balik Modal", days: "hari",
        myDevices: "Perangkat Saya", empty: "Kosong", bonus: "BONUS",
        withdraw: "Tarik TON", enterAmount: "Jumlah", minWithdraw: "Minimum 100 TON",
        walletAddress: "Alamat Dompet", withdrawBtn: "Tarik", connectFirst: "Hubungkan Dompet!",
        invalidAmount: "Jumlah tidak valid!", minRequired: "Minimum 100 TON", noBalance: "Saldo tidak cukup!",
        referralTitle: "Program Referral", yourCode: "Kode Anda", totalRefs: "Total Referral",
        commission: "Komisi", shareLink: "Bagikan Link", copied: "Disalin!",
        terms: "Ketentuan", privacy: "Privasi", lastUpdated: "Terakhir Diperbarui",
        offlineTitle: "Selamat Datang!", offlineSub: "Penambang bekerja saat Anda pergi",
        dailyReward: "Hadiah Harian", claimReward: "KLAIM", day: "Hari",
        sent: "Mengirim...", cancelled: "Dibatalkan", opening: "Membuka...",
        tasksTitle: "Tugas & Pencapaian", tasksSubtitle: "Selesaikan tugas untuk mendapat bonus TON!"
    },
    fr: {
        langName: "Français", totalBalance: "SOLDE TOTAL", connect: "Connecter", connected: "Connecté",
        ghsUnit: "GH/s", networkStatus: "État Réseau", offline: "Hors ligne ○", mining: "Minage ●",
        active: "Actif", activeDevices: "Appareils", dailyTon: "TON Quotidien",
        freeNode: "Nœud GRATUIT", freeNodeDesc: "+300 GH/s (30 min)", watch: "REGARDER",
        joinChannel: "Rejoindre Canal", channelDesc: "Actualités et cadeaux",
        dailySpin: "Tour Quotidien", spinDesc: "Tournez et gagnez!", nextSpinIn: "Prochain tour", free: "GRATUIT",
        bronze: "Bronze", silver: "Argent", gold: "Or", diamond: "Diamant", legendary: "Légendaire",
        maxRank: "RANG MAX", tonEarned: "TON gagnés", toNext: "→",
        dailyFortune: "Fortune", spinToWin: "TOURNER", spinning: "En cours...",
        addedBalance: "Ajouté au solde!", nextSpinInLabel: "Prochain tour:",
        hardwareStore: "Boutique", tonDay: "TON/jour", roi: "Retour", days: "jours",
        myDevices: "Mes Appareils", empty: "Vide", bonus: "BONUS",
        withdraw: "Retirer TON", enterAmount: "Montant", minWithdraw: "Minimum 100 TON",
        walletAddress: "Adresse Portefeuille", withdrawBtn: "Retirer", connectFirst: "Connectez Portefeuille!",
        invalidAmount: "Montant invalide!", minRequired: "Minimum 100 TON", noBalance: "Solde insuffisant!",
        referralTitle: "Programme Parrainage", yourCode: "Votre Code", totalRefs: "Total Parrainages",
        commission: "Commission", shareLink: "Partager Lien", copied: "Copié!",
        terms: "Conditions", privacy: "Confidentialité", lastUpdated: "Mise à jour",
        offlineTitle: "Bon retour!", offlineSub: "Vos mineurs ont travaillé pendant votre absence",
        dailyReward: "Récompense", claimReward: "RÉCLAMER", day: "Jour",
        sent: "Envoi...", cancelled: "Annulé", opening: "Ouverture...",
        tasksTitle: "Tâches et Réalisations", tasksSubtitle: "Complétez les tâches pour gagner du TON bonus !"
    },
    de: {
        langName: "Deutsch", totalBalance: "GESAMTGUTHABEN", connect: "Verbinden", connected: "Verbunden",
        ghsUnit: "GH/s", networkStatus: "Netzwerkstatus", offline: "Offline ○", mining: "Mining ●",
        active: "Aktiv", activeDevices: "Aktive Geräte", dailyTon: "Täglicher TON",
        freeNode: "Kostenloser Knoten", freeNodeDesc: "+300 GH/s (30 Min)", watch: "ANSEHEN",
        joinChannel: "Kanal beitreten", channelDesc: "Neuigkeiten",
        dailySpin: "Tägliches Drehen", spinDesc: "Drehen und gewinnen!", nextSpinIn: "Nächste Drehung", free: "GRATIS",
        bronze: "Bronze", silver: "Silber", gold: "Gold", diamond: "Diamant", legendary: "Legendär",
        maxRank: "MAX RANG", tonEarned: "Verdiente TON", toNext: "→",
        dailyFortune: "Tägliches Glück", spinToWin: "DREHEN", spinning: "Dreht sich...",
        addedBalance: "Zum Guthaben hinzugefügt!", nextSpinInLabel: "Nächste Drehung:",
        hardwareStore: "Hardware-Shop", tonDay: "TON/Tag", roi: "Amortisation", days: "Tage",
        myDevices: "Meine Geräte", empty: "Leer", bonus: "BONUS",
        withdraw: "TON abheben", enterAmount: "Betrag", minWithdraw: "Minimum 100 TON",
        walletAddress: "Wallet-Adresse", withdrawBtn: "Abheben", connectFirst: "Wallet verbinden!",
        invalidAmount: "Ungültiger Betrag!", minRequired: "Minimum 100 TON", noBalance: "Guthaben reicht nicht!",
        referralTitle: "Empfehlungsprogramm", yourCode: "Ihr Code", totalRefs: "Empfehlungen",
        commission: "Provision", shareLink: "Link teilen", copied: "Kopiert!",
        terms: "Nutzungsbedingungen", privacy: "Datenschutz", lastUpdated: "Aktualisierung",
        offlineTitle: "Willkommen zurück!", offlineSub: "Ihre Miner haben während Ihrer Abwesenheit gearbeitet",
        dailyReward: "Tägliche Belohnung", claimReward: "EINLÖSEN", day: "Tag",
        sent: "Sende...", cancelled: "Abgebrochen", opening: "Öffne...",
        tasksTitle: "Aufgaben & Erfolge", tasksSubtitle: "Aufgaben erledigen und Bonus-TON verdienen!"
    },
    vi: {
        langName: "Tiếng Việt", totalBalance: "TỔNG SỐ DƯ", connect: "Kết nối", connected: "Đã kết nối",
        ghsUnit: "GH/s", networkStatus: "Trạng thái Mạng", offline: "Ngoại tuyến ○", mining: "Đang đào ●",
        active: "Hoạt động", activeDevices: "Thiết bị", dailyTon: "TON Hàng ngày",
        freeNode: "Node MIỄN PHÍ", freeNodeDesc: "+300 GH/s (30 phút)", watch: "XEM",
        joinChannel: "Tham gia Kênh", channelDesc: "Tin tức và phần thưởng",
        dailySpin: "Quay Hàng ngày", spinDesc: "Quay nhận TON miễn phí!", nextSpinIn: "Lượt quay tiếp", free: "MIỄN PHÍ",
        bronze: "Đồng", silver: "Bạc", gold: "Vàng", diamond: "Kim cương", legendary: "Huyền thoại",
        maxRank: "HẠNG CAO NHẤT", tonEarned: "TON đã kiếm", toNext: "→",
        dailyFortune: "Vận may", spinToWin: "QUAY VÀ THẮNG", spinning: "Đang quay...",
        addedBalance: "Đã thêm vào số dư!", nextSpinInLabel: "Lượt quay tiếp:",
        hardwareStore: "Cửa hàng", tonDay: "TON/ngày", roi: "Hoàn vốn", days: "ngày",
        myDevices: "Thiết bị", empty: "Trống", bonus: "THƯỞNG",
        withdraw: "Rút TON", enterAmount: "Số tiền", minWithdraw: "Tối thiểu 100 TON",
        walletAddress: "Địa chỉ Ví", withdrawBtn: "Rút", connectFirst: "Kết nối Ví!",
        invalidAmount: "Không hợp lệ!", minRequired: "Tối thiểu 100 TON", noBalance: "Không đủ!",
        referralTitle: "Chương trình Giới thiệu", yourCode: "Mã của bạn", totalRefs: "Tổng",
        commission: "Hoa hồng", shareLink: "Chia sẻ Liên kết", copied: "Đã sao chép!",
        terms: "Điều khoản", privacy: "Bảo mật", lastUpdated: "Cập nhật",
        offlineTitle: "Chào mừng trở lại!", offlineSub: "Máy đào đã hoạt động khi bạn vắng",
        dailyReward: "Phần thưởng", claimReward: "NHẬN", day: "Ngày",
        sent: "Đang gửi...", cancelled: "Đã hủy", opening: "Đang mở...",
        tasksTitle: "Nhiệm vụ & Thành tích", tasksSubtitle: "Hoàn thành nhiệm vụ để nhận TON thưởng!"
    },
    th: {
        langName: "ไทย", totalBalance: "ยอดรวม", connect: "เชื่อมต่อ", connected: "เชื่อมต่อแล้ว",
        ghsUnit: "GH/s", networkStatus: "สถานะเครือข่าย", offline: "ออฟไลน์ ○", mining: "กำลังขุด ●",
        active: "ใช้งาน", activeDevices: "อุปกรณ์", dailyTon: "TON รายวัน",
        freeNode: "โหนดฟรี", freeNodeDesc: "+300 GH/s (30 นาที)", watch: "ดู",
        joinChannel: "เข้าร่วมช่อง", channelDesc: "ข่าวสารและรางวัล",
        dailySpin: "หมุนรายวัน", spinDesc: "หมุนรับ TON ฟรี!", nextSpinIn: "หมุนต่อไป", free: "ฟรี",
        bronze: "บรอนซ์", silver: "เงิน", gold: "ทอง", diamond: "เพชร", legendary: "ตำนาน",
        maxRank: "สูงสุด", tonEarned: "TON ที่ได้", toNext: "→",
        dailyFortune: "โชคประจำวัน", spinToWin: "หมุนเพื่อชนะ", spinning: "กำลังหมุน...",
        addedBalance: "เพิ่มในยอดแล้ว!", nextSpinInLabel: "หมุนต่อไป:",
        hardwareStore: "ร้านฮาร์ดแวร์", tonDay: "TON/วัน", roi: "คืนทุน", days: "วัน",
        myDevices: "อุปกรณ์ของฉัน", empty: "ว่าง", bonus: "โบนัส",
        withdraw: "ถอน TON", enterAmount: "จำนวน", minWithdraw: "ขั้นต่ำ 100 TON",
        walletAddress: "ที่อยู่กระเป๋า", withdrawBtn: "ถอน", connectFirst: "เชื่อมต่อกระเป๋า!",
        invalidAmount: "ไม่ถูกต้อง!", minRequired: "ขั้นต่ำ 100 TON", noBalance: "ยอดไม่พอ!",
        referralTitle: "โปรแกรมแนะนำ", yourCode: "รหัส", totalRefs: "แนะนำทั้งหมด",
        commission: "คอมมิชชั่น", shareLink: "แชร์ลิงก์", copied: "คัดลอกแล้ว!",
        terms: "ข้อกำหนด", privacy: "ความเป็นส่วนตัว", lastUpdated: "อัปเดตล่าสุด",
        offlineTitle: "ยินดีต้อนรับกลับ!", offlineSub: "เครื่องขุดทำงานขณะคุณไม่อยู่",
        dailyReward: "รางวัลประจำวัน", claimReward: "รับรางวัล", day: "วัน",
        sent: "กำลังส่ง...", cancelled: "ยกเลิก", opening: "กำลังเปิด...",
        tasksTitle: "ภารกิจและความสำเร็จ", tasksSubtitle: "ทำภารกิจเพื่อรับ TON โบนัส!"
    },
    fil: {
        langName: "Filipino", totalBalance: "KABUUANG BALANSE", connect: "Ikonekta", connected: "Nakakonekta",
        ghsUnit: "GH/s", networkStatus: "Status ng Network", offline: "Offline ○", mining: "Nagmimina ●",
        active: "Aktibo", activeDevices: "Aktibong Device", dailyTon: "TON Araw-araw",
        freeNode: "LIBRENG Node", freeNodeDesc: "+300 GH/s (30 min)", watch: "PANOORIN",
        joinChannel: "Sumali sa Channel", channelDesc: "Balita at giveaway",
        dailySpin: "Daily Spin", spinDesc: "I-spin at manalo!", nextSpinIn: "Susunod na spin", free: "LIBRE",
        bronze: "Bronze", silver: "Silver", gold: "Gold", diamond: "Diamond", legendary: "Legendary",
        maxRank: "MAX RANK", tonEarned: "TON na nakuha", toNext: "→",
        dailyFortune: "Daily Fortune", spinToWin: "SPIN AT MANALO", spinning: "Umiikot...",
        addedBalance: "Naidagdag sa balanse!", nextSpinInLabel: "Susunod:",
        hardwareStore: "Hardware Store", tonDay: "TON/araw", roi: "Balik-puhunan", days: "araw",
        myDevices: "Mga Device Ko", empty: "Walang laman", bonus: "BONUS",
        withdraw: "Mag-withdraw", enterAmount: "Halaga", minWithdraw: "Minimum 100 TON",
        walletAddress: "Wallet Address", withdrawBtn: "Withdraw", connectFirst: "Ikonekta Wallet!",
        invalidAmount: "Di-valid!", minRequired: "Minimum 100 TON", noBalance: "Kulang ang balanse!",
        referralTitle: "Referral Program", yourCode: "Iyong Code", totalRefs: "Total",
        commission: "Komisyon", shareLink: "I-share Link", copied: "Nakopya!",
        terms: "Mga Tuntunin", privacy: "Privacy", lastUpdated: "Huling Na-update",
        offlineTitle: "Welcome Back!", offlineSub: "Nagtatrabaho ang mga miner mo habang wala ka",
        dailyReward: "Daily Reward", claimReward: "KUNIN", day: "Araw",
        sent: "Ipinapadala...", cancelled: "Kinansela", opening: "Binubuksan...",
        tasksTitle: "Mga Gawain at Tagumpay", tasksSubtitle: "Kumpletuhin ang mga gawain para makakuha ng bonus TON!"
    },
    bn: {
        langName: "বাংলা", totalBalance: "মোট ব্যালেন্স", connect: "সংযুক্ত করুন", connected: "সংযুক্ত",
        ghsUnit: "GH/s", networkStatus: "নেটওয়ার্ক", offline: "অফলাইন ○", mining: "মাইনিং ●",
        active: "সক্রিয়", activeDevices: "সক্রিয় ডিভাইস", dailyTon: "দৈনিক TON",
        freeNode: "ফ্রি নোড", freeNodeDesc: "+300 GH/s (30 মিনিট)", watch: "দেখুন",
        joinChannel: "চ্যানেলে যোগ দিন", channelDesc: "খবর ও পুরস্কার",
        dailySpin: "দৈনিক স্পিন", spinDesc: "ঘুরান ও TON জিতুন!", nextSpinIn: "পরবর্তী স্পিন", free: "ফ্রি",
        bronze: "ব্রোঞ্জ", silver: "সিলভার", gold: "গোল্ড", diamond: "ডায়মন্ড", legendary: "কিংবদন্তি",
        maxRank: "সর্বোচ্চ", tonEarned: "অর্জিত TON", toNext: "→",
        dailyFortune: "দৈনিক ভাগ্য", spinToWin: "ঘুরান ও জিতুন", spinning: "ঘুরছে...",
        addedBalance: "ব্যালেন্সে যোগ হয়েছে!", nextSpinInLabel: "পরবর্তী:",
        hardwareStore: "হার্ডওয়্যার স্টোর", tonDay: "TON/দিন", roi: "ফেরত", days: "দিন",
        myDevices: "আমার ডিভাইস", empty: "খালি", bonus: "বোনাস",
        withdraw: "TON উত্তোলন", enterAmount: "পরিমাণ", minWithdraw: "সর্বনিম্ন 100 TON",
        walletAddress: "ওয়ালেট ঠিকানা", withdrawBtn: "উত্তোলন", connectFirst: "ওয়ালেট সংযুক্ত করুন!",
        invalidAmount: "অবৈধ!", minRequired: "সর্বনিম্ন 100 TON", noBalance: "পর্যাপ্ত নেই!",
        referralTitle: "রেফারেল প্রোগ্রাম", yourCode: "আপনার কোড", totalRefs: "মোট",
        commission: "কমিশন", shareLink: "লিংক শেয়ার করুন", copied: "কপি হয়েছে!",
        terms: "শর্তাবলী", privacy: "গোপনীয়তা", lastUpdated: "সর্বশেষ আপডেট",
        offlineTitle: "স্বাগতম!", offlineSub: "আপনার অনুপস্থিতিতে মাইনাররা কাজ করেছে",
        dailyReward: "দৈনিক পুরস্কার", claimReward: "পুরস্কার নিন", day: "দিন",
        sent: "পাঠানো হচ্ছে...", cancelled: "বাতিল", opening: "খুলছে...",
        tasksTitle: "কাজ ও অর্জন", tasksSubtitle: "কাজ সম্পন্ন করে বোনাস TON আয় করুন!"
    }
};

function detectLanguage() {
    try {
        const saved = localStorage.getItem('tonminer_lang');
        if (saved && LANG[saved]) return saved;
        if (window.Telegram && window.Telegram.WebApp) {
            const tgLang = window.Telegram.WebApp.initDataUnsafe?.user?.language_code;
            if (tgLang && LANG[tgLang]) return tgLang;
            const map = { 'zh-hans': 'zh', 'zh-hant': 'zh', 'pt-br': 'pt', 'tl': 'fil' };
            if (tgLang && map[tgLang]) return map[tgLang];
        }
        const bl = (navigator.language || '').split('-')[0];
        if (LANG[bl]) return bl;
    } catch (e) {}
    return 'en';
}

let currentLang = detectLanguage();
function t(key) { return (LANG[currentLang] && LANG[currentLang][key]) || LANG.en[key] || key; }
function setLanguage(lang) { if (LANG[lang]) { currentLang = lang; localStorage.setItem('tonminer_lang', lang); } }
function getAvailableLanguages() { return Object.keys(LANG).map(code => ({ code, name: LANG[code].langName })); }

export { LANG, t, currentLang, setLanguage, detectLanguage, getAvailableLanguages };
